elementary/wingpanel

CMakeLists.txt

data: install wingpanel.svg

---

src/Wingpanel.vala

Update URLs in About dialog

---

lib/Widgets/Button.vala
lib/Widgets/Container.vala
lib/Widgets/Switch.vala

* Use GObject-style
* Reassign ambiguous "wingpanel developers" to elementary LLC

Container.vala: use GObject style

---

lib/Widgets/OverlayIcon.vala

OverlayIcon.vala: Simplify, use construct

---

src/PanelWindow.vala

* Make use of `Object ()`
* Organize
* Remove extra whitespace
* Add `skip_pager_hint`

PanelWindow.vala: Use Object and organize

---

lib/Indicator.vala
lib/IndicatorManager.vala
lib/Widgets/AutomaticScrollBox.vala
lib/Widgets/Button.vala
lib/Widgets/Container.vala
lib/Widgets/OverlayIcon.vala
lib/Widgets/Separator.vala
lib/Widgets/Switch.vala
sample/SampleIndicator.vala
src/PanelWindow.vala
src/Services/BackgroundManager.vala
src/Services/IndicatorSorter.vala
src/Services/PopoverManager.vala
src/Services/Settings.vala
src/Widgets/IndicatorEntry.vala
src/Widgets/IndicatorMenuBar.vala
src/Widgets/IndicatorPopover.vala
src/Widgets/MenuBar.vala
src/Widgets/Panel.vala
src/Widgets/StyleClass.vala
src/Wingpanel.vala
wingpanel-interface/BackgroundManager.vala
wingpanel-interface/DBusServer.vala
wingpanel-interface/FocusManager.vala
wingpanel-interface/Main.vala
wingpanel-interface/Settings.vala
wingpanel-interface/Utils.vala

Updates the Free Software Foundation address in license headers
Fixes https://bugs.launchpad.net/wingpanel/+bug/1653413

Update FSF address

---

src/Services/PopoverManager.vala

Stop clicking blank space from closing indicator popover

---

lib/Widgets/Container.vala
lib/Widgets/Switch.vala

The old API remains and is just deprecated

WidgetSwitch: use a more modern API

---

.travis.yml
CMakeLists.txt
src/Services/PopoverManager.vala

Fixes a regression caused by API changes that broke animations

Restore animating popovers

---

lib/IndicatorManager.vala

Do not load modules with wrong suffix

---

src/Wingpanel.vala

Adds a commandline arg to run wingpanel as a greeter type server. This would allow us to use wingpanel proper in the greeter instead of carrying a custom panel there

Add the option to run wingpanel as a greeter type

---

wingpanel-interface/BackgroundManager.vala

Fix: Wingpanel on multiple monitors not grabbing the window on primary monitor

---

lib/Widgets/Switch.vala

Fix stretched switches as seen in https://github.com/elementary/stylesheet/issues/401https://github.com/elementary/stylesheet/issues/401

Switch: valign center

---

src/PanelWindow.vala
src/Services/PopoverManager.vala

Fixes: #152 
Also removes arbitrary timeout.

Use unmap signal to shrink window

---

wingpanel-interface/FocusManager.vala

Fix focus on dialogs started from wingpanel

---

data/styles/application.css
src/Widgets/Panel.vala

Partially addresses #2 
Only includes panel styles, doesn't affect indicators themselves yet

Move panel css to resource

---

src/Widgets/Panel.vala

Doesn't seem like we ever set this anywhere

Panel: Remove unused if def

---

data/wingpanel.appdata.xml.in

I have not tagged this as a release commit so that we can generate translations

AppData: add release info for 2.2.6

---

data/wingpanel.appdata.xml.in
meson.build

https://github.com/elementary/wingpanel/compare/2.2.5...master

Release 2.2.6

---

data/autostart.desktop
data/meson.build
data/wingpanel.desktop.in

Add an autostart.desktop like we do in Onboarding

Add autostart.desktop

---

src/Services/BackgroundManager.vala
wingpanel-interface/DBusServer.vala

dbus: Add GLib.Error to all D-Bus methods

---

data/styles/application.css

3px on each side is 6px :)
This seems like a super common request and a reason a lot of people try to add custom CSS

Application.css: reduce padding to 6px

---

src/Wingpanel.vala

Same as https://github.com/elementary/pantheon-agent-polkit/pull/58 (copy and paste error)

Fix end-session signal signature

---

src/Widgets/IndicatorEntry.vala

* Bump copyright
* GObject-style construction
* Properties cleanup
* Remove unnecessary "this"

IndicatorEntry: Use GObject-style

---

src/Widgets/IndicatorPopover.vala

IndicatorPopover: Code style cleanup

---

src/Services/PopoverManager.vala

Fixes #392 
@pongloongyeat  I am unable to assign reviewers - would you mind reviewing or requesting appropriate developer to look at this?

Suppress tooltips when popover is open

---

README.md

README: Mention how to temporarily stop auto-restart behavior

---

vapi/Clutter-10.metadata
vapi/Meta-10.metadata
vapi/libmutter.vapi
vapi/mutter-clutter.vapi
vapi/mutter-cogl-6.vapi

Synchronize the .vapi with Gala

---

src/Widgets/IndicatorEntry.vala

Requires for elementary/wingpanel-indicator-power#232

Listen to smooth scroll events

---

src/PanelWindow.vala

Close popover on Esc

---

src/PanelWindow.vala

Replace window moving animation stuff with a Gtk.Revealer

PanelWindow: animate in with Gtk.Revealer

---

data/wingpanel.appdata.xml.in

Contains a bugfix and a small new feature. It would be nice to release a new version before introducing significant changes (#492 or #481)

3.0.4 release notes

---

data/wingpanel.appdata.xml.in
src/Application.vala

Make sure people can't break styles even if they try to change the system stylesheet or icons

Application: hard code elementary styles

---

lib/Indicator.vala
src/Services/IndicatorSorter.vala

Make the panel aware of and sort https://github.com/elementary/quick-settings

Add sorting for QuickSettings

---

debian/io.elementary.wingpanel.postinst

Remove old autostart in postinst

---

data/styles/Application.css
data/wingpanel.metainfo.xml.in

CSS: add padding between text and icons

---

src/PanelWindow.vala

Fix crash on X11

---

schemas/io.elementary.desktop.wingpanel.gschema.xml
src/Services/WMDBus.vala
src/Widgets/IndicatorEntry.vala
src/Widgets/Panel.vala
src/meson.build

Switch workspace when scrolling on the panel

---

src/PanelWindow.vala
src/Services/DisplayConfig.vala
src/meson.build

Scale dimensions if we have a physical monitor layout

---

data/styles/Application.css

Fixes #552 
Make sure the panel height doesn't change dramatically between styles

CSS: fix changing panel height

---

src/PanelWindow.vala

Fixes #568 
Not sure why but this works :shrug:

PanelWindow: Only multiply by scale factor on wayland

---

src/Services/PopoverManager.vala

PopoverManager: Simplify owner button press recognition

---

sample/SampleIndicator.vala

SampleIndicator: GTK4 prep

---

.github/workflows/main.yml
vapi/Clutter-15-custom.vala
vapi/Clutter-15.metadata
vapi/Cogl-15-custom.vala
vapi/Cogl-15.metadata
vapi/Mtk-15.metadata
vapi/config.vapi
vapi/libmutter-15.deps
vapi/libmutter-15.vapi
vapi/libmutter.vapi
vapi/meson.build
vapi/mutter-clutter-15.deps
vapi/mutter-clutter-15.vapi
vapi/mutter-clutter.vapi
vapi/mutter-cogl-14.deps
vapi/mutter-cogl-14.vapi
vapi/mutter-cogl-15.deps
vapi/mutter-cogl-15.vapi
vapi/mutter-cogl-pango-15.vapi
vapi/mutter-cogl-pango.vapi
vapi/mutter-mtk-13.vapi
vapi/mutter-mtk-15.vapi
wingpanel-interface/meson.build

I use some files from [gala](https://github.com/elementary/gala/pull/2090/files), and the wingpannel builds, with the new version!!

Updated To Mutter47 (libmutter-15)

---

meson.build

Waiting #598 to be merged first.

Release 8.0.2
