elementary/wingpanel

src/Wingpanel.vala
`Gtk.init` call isn't needed here since the application class subclasses`Granite.Application` which is also subclassing `Gtk.Application` which takes care of initializing Gtk.
=> Remove unnecessary init () call

src/PanelWindow.vala
Fixes `gtk_window_resize` warnings. There is no point in resizing the window if the `monitor_width` wasn't assigned yet.
=> Fix resize warnings

lib/IndicatorManager.vala
A classic example of removing something from the list in the iteration loop was causing segfaults because of accessing memory that's non existent. I've also fixed the problem that the indicators were tried to be deregistered even if they weren't registered, resulting in warnings like `[03:09:54.929258 Critical] wingpanel_indicator_manager_deregister_indicator: assertion 'indicator != NULL' failed`. This should partially fix #21. The wingpanel will still restart because there are some indicators that don't put their `Wingpanel.Indicator` in any namespace and that also results in a crash e.g: notifications-indicator. A really easy way of testing that is just duplicating the .so file in the Wingpanel's plugin directory.
=> Fix segfaults and deregister warnings

src/PanelWindow.vala, src/Widgets/Panel.vala
Fixes #7. Makes it possible to use Ctrl+Tab to cycle through indicators. Wingpanel will cycle only when some indicator is currently opened, otherwise, never. To determine the next sibling of the currently opened indicator, I've created `get_next_sibling` helper method in `Wingpanel.Panel` which implements a simple algorithm:
1. Check in what menubar the current indicator is located.
2. If on the left:
- if indicator not found in the menubar, return `null`
- if it's the last indicator in this menubar, return the first one from the center menubar (if exists)
- otherwise, return the next one in this menubar
The same goes for the center and right menubar, except that these will return the next menubar so for center menubar the next will be the right one, and for the right menubar (that is the …
=> Cycle indicators

src/PanelWindow.vala, src/Services/BackgroundManager.vala
This branch makes it so wingpanel will try to reconnect to it's DBus bridge between itself and Gala plugin when it re-appears. This should make wingpanel more relible in some unlikely of cases e.g: Gala crashes. 
This is also much nicer to work with when you're writing code for Gala, testing and restarting the WM. Wingpanel will automatically reconnect to the interface when it appears. On master, this just makes wingpanel disconnect from the interface and not react to any state changes.
=> Reconnect to DBus interface when it re-appears

src/Services/PopoverManager.vala
Fixes #62 
The allocation of the `Gtk.Box` containing the indicator popover is used to determine if a click was inside the popover or not when deciding whether or not that click event should close the currently open popover.
Because an `Allocation` is relative to its parent this was always `(0, 0)` causing there to be a box the size of the current indicator popover to be in the top left that prevented you from clicking to close indicators. So, this PR does some maths to move the allocation calculation underneath the actual popover relative to the mouse co-ordinates.
I considered removing the mouse bounds check altogether as items inside the popover still receive click events properly. But removing it causes the application menu to be closed when clicking a blank space inside it, so not …
=> Calculate actual popover position for mouse event detection

lib/Widgets/Button.vala
There is now a Gtk widget that provides this same functionality
=> Deprecate Widgets.Button in favor of Gtk.ModelButton

wingpanel-interface/CMakeLists.txt
fedora has just introduced stricter linker flags, and it turns out, the wingpanel interface was missing the flag to be linked against libm.
=> CMakeLists.txt: add missing -lm linker flag

src/Services/IndicatorSorter.vala
@stsdc is developing a system monitor wingpanel indicator and it was appearing between the sound and keyboard indicators.
Because the keyboard indicator was at position 0 of the array, it was being alphabetically sorted with the ayatana indicators and any other indicators that came along and weren't defined.
I've taken this opportunity to add "codenames" for both of those categories so we can ensure a consistent sort order with the system indicators sorted after everything else.
This maintains ayatana compatibility for now in case we want to release a new version of wingpanel in the mean time. I assume another PR will come along and rip out the ayatana support at some point :smile:
=> Fix 3rd party indicator ordering

wingpanel-interface/Utils.vala
Fixes https://github.com/elementary/gala/issues/221
For some reason the X11 backend for Clutter didn't like that we start processing something and interrupt Clutter events. This fixes that by simply fireing the signal at a later time so Clutter takes it's time to process everything and then start updatng the background color info with `Idle.add`.
=> Fix gala hanging when moving a window while changing a wallpaper

src/PanelWindow.vala
The scale factor is being accounted for when setting the height but
not the width. Be sure it's set for both.
Fixes: https://github.com/elementary/wingpanel/issues/92
=> Fix the width of struts on HiDPI displays

src/Widgets/Panel.vala
The coordinates returned from the event need to be multiplied by
the scale factor.
Fixes: https://github.com/elementary/wingpanel/issues/134
=> Fix dragging from panel on HiDPI displays

wingpanel-interface/FocusManager.vala
Bitesize change that prevents dragging minimized and fullscreened windows from the panel, this is possible right now in master.
=> Fix dragging a minimized window

README.md
Also libgala-dev and  libmutter-2-dev are needed in order to build succesfully.
=> Update README.md: Add necessary dependencies.

src/Widgets/IndicatorEntry.vala, src/Widgets/IndicatorMenuBar.vala
Fixes: elementary/wingpanel-indicator-bluetooth#64
Supersedes: #174
After the bluetooth indicator disappears it sometimes doesn't properly re-appear. 
This can be reproduced by running:
```
systemctl restart bluetooth
```
I can also reproduce the issue by rapidly switching nightlight on off. You see it sometimes not showing up or even showing only half of the icon:
(Using <kbd>Enter</kbd> to switch the button makes this easier)
I noticed I could fix this by commenting the delayed re-ordering:
https://github.com/elementary/wingpanel/blob/master/src/Widgets/IndicatorEntry.vala#L82-L85
But this means the indicator isn't removed and you'll see extra margins. 
Removing the previous timeout and increasing the interval helps a great deal. But that means another arbitrary value, which could still …
=> Fix revealer using unmap event

src/Widgets/Panel.vala
Fixes: #130
I noticed that sometimes my wingpanel would overlap left/right tiled windows. Looking into it it seemed like the allocated height of the panel changed from 24 (the requested height) to 30. For some people, in some cases this switch would happen after the [slide in animation](https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L76-L86) where the [truts](https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L126-L153)? are updated. 
I filtered out all indicators and it seemed like these indicators caused the panel's height to go from 24 to 30:
- [session](https://github.com/elementary/wingpanel-indicator-session)
- [network](https://github.com/elementary/wingpanel-indicator-network)
- …
=> Fix wingpanel potentially overlapping windows

wingpanel-interface/BackgroundManager.vala
Fixes https://github.com/elementary/gala/issues/497.
Changing the workspace of a window didn't cause an update to the wingpanel background state. Now it does.
=> Fix moving window to another workspace not updating wingpanel state

wingpanel-interface/FocusManager.vala
Fixes: #205 and https://github.com/elementary/applications-menu/issues/19
Following @davidmhewitt advice to listen for window focus changes fixing the following hypothesis:
> Smaller, faster apps manage to open their window and grab focus before this code restores the (wrong) previously focused window. Whereas slower apps take focus after the previously focused window has been given focus back.
=> Keep better record of focused apps

wingpanel-interface/Utils.vala
Fixes #207 
The new mutter version seems to give us a texture that's 3px in both dimensions bigger than the background actor that the texture is rendered from. This tends to leave a darker border around the texture, which doesn't help the calculations.
Adjust the logic to ignore 2px from every side of the texture we pull from clutter and also fix the following logic errors while we're here:
- Luminance calculations were being done with reversed RGB values
- Copy and paste error in argument range check
- Calculations didn't account for an offset start position other than 0 and would only calculate on an area of (requested size - offset) rather than the requested area
This will need testing with a variety of backgrounds again to make sure it's doing sensible things, but it seems much closer …
=> Fix panel transparency calculations

data/meson.build, data/styles/application.css, data/wingpanel.gresource.xml, meson.build, src/PanelWindow.vala, src/meson.build
Fixes #169 
We were inheriting `-GtkWidget-window-dragging: true;` from `Gtk.STYLE_CLASS_MENUBAR` which was causing the issue of being able to drag the panel around with 2+ fingers on a touchscreen.
I don't know if we want to do this in a neater way (i.e. in a GResource or by doing something in the stylesheet), but this seems to be the cause of the issue and fixes it for me.
=> Disable GtkWidget-window-dragging on panel

src/Services/PopoverManager.vala
`Gtk.Widget.get_root_window` is deprecated
Since `owner` is a Gtk.Window (and thus a Gtk.Widget subclass), it seems like we can just use `get_allocated_width` here right?
=> PopoverManager: use allocated_width

src/SessionManager.vala, src/Wingpanel.vala, src/meson.build
To be tested in conjunction with #274 
Session manager code copied verbatim from polkit agent and just re-namespaced so copyright headers left intact.
May need to do the equivalent for plank too if this fixes the delayed startup thing @danrabbit was seeing while testing #274 .
=> Register with the session manager

sample/SampleIndicator.vala
`display_name` & `description` were deprecated in https://github.com/elementary/wingpanel/commit/86098c2059e7fa6af82f888f755aeec31d00fd31
=> Remove deprecated properties from SampleIndicator

lib/Widgets/Separator.vala
If we really need this convenience, it should probably be a stylesheet feature instead
=> Separator: Mark as deprecated

lib/Indicator.vala, src/Services/IndicatorSorter.vala
This adds the following three constants:
```vala
public const string NIGHT_LIGHT = "nightlight";
public const string PRIVACY = "privacy";
public const string ACCESSIBILITY = "a11y";
```
Let me know if the indicator sorting as in #366 should be in this PR. I've left it out of this PR so the design team can add it in instead.
=> Add codenames for missing indicators

debian/libwingpanel-3.0-0.install
This package shouldn't install the `libwingpanel-3.0.so` symlink as this is in the `-dev` package.
=> deb-packaging: Fix .so version installation

data/styles/application.css
Fixes #317 
This makes colors in icons change based on the panel color itself, not on whether popovers are light or dark
=> Application.css: Hard code -gtk-icon-palette

data/wingpanel.appdata.xml.in
WingPanel is not what you'd consider a desktop app, and components like Gala lack this type definition. May resolve https://github.com/elementary/appcenter/issues/1758
=> AppData: Remove desktop app type

src/Application.vala, src/Widgets/Panel.vala
This is kind of a hotfix for startup delays on the greeter. I'm not sure what the proper long-term solution should be, but this resolves it in a simple way
=> Application: Only load dark style preference in session

debian/control
Makes it more clear that this is a build dependency and allows us to bump this to cause a rebuild if the versions change.
=> deb-packaging: Explicitly add libmutter deps

src/Services/BackgroundManager.vala
Currently, if you run wingpanel on a compositor that doesn't have the Gala DBus interface for checking the wallpaper colour, it defaults to a fully transparent light style which may not be ideal depending on the wallpaper.
It would be better to just have to solid black maximized panel in cases where the Gala DBus interface isn't available. This would either be because the compositor isn't Gala and doesn't implement the interface, or because Gala crashed (and you've got bigger issues than the colour of your panel)
=> Fallback to maximized style if Gala bus is unavailable

data/styles/application.css, data/styles/panel.css, src/PanelWindow.vala, src/Widgets/IndicatorEntry.vala
Some style fixes ahead of Gtk4 to reduce the diff there
* Fix CSS syntax error with `alpha`
* Remove old `window-dragging`
* Set a min-height to avoid divide by zero
* Don't see `menubar` because it doesn't seem like there's a reason to set it here and the class doesn't exist in Gtk4
* Remove hardcoded margin in IndicatorEntry
=> Styles: fix CSS syntax, remove extra class

data/wingpanel.appdata.xml.in, src/Widgets/IndicatorMenuBar.vala
Prevents the MenuBar to allocate space for the previous position of this.
Closes: https://github.com/elementary/wingpanel/issues/502
=> IndicatorMenuBar: Do not try to readd an already added child

wingpanel-interface/Utils.vala
Uses `BackgroundManagerInterface` from https://github.com/elementary/gala/pull/1859
=> Use BackgroundManager to get wallpaper

wingpanel-interface/Main.vala
Original commit message:  
> Fix typos  
> Changed private void method name `on_bus_aquired` to `on_bus_acquired`
I fixed a typo in the aforementioned method declaration.
=> Fixed some typos in a method declaration

wingpanel-interface/FocusManager.vala
Fixes crash that can occur when opening slingshot:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007582916f1549 in meta_window_focus (window=window@entry=0x603df009b880, timestamp=0) at ../src/core/window.c:4670
[Current thread is 1 (Thread 0x75828faeeb00 (LWP 1758))]
(gdb) bt
#0  0x00007582916f1549 in meta_window_focus (window=window@entry=0x603df009b880, timestamp=0) at ../src/core/window.c:4670
#1  0x000075828848a1d1 in wingpanel_interface_focus_manager_restore_focused_window (self=0x603defc3a9d0 [WingpanelInterfaceFocusManager])
at wingpanel-interface/libwingpanel-interface.so.p/FocusManager.c:246
#2  0x000075828848a3f6 in wingpanel_interface_dbus_server_restore_focused_window (self=self@entry=0x603def19b0f0 [WingpanelInterfaceDBusServer], …
```
=> FocusManager: Make sure to never reuse a freed Window

meson.build, protocol/meson.build, protocol/pantheon-desktop-shell-v1.xml, protocol/pantheon-desktop-shell.deps, protocol/pantheon-desktop-shell.vapi, src/Application.vala, src/PanelWindow.vala, src/meson.build, vapi/gdk-wayland-3.0.vapi
=> Use wayland protocol for positioning

src/PanelWindow.vala
Keep it always revealed on wayland since animating in is done by gala. Also we don't need the size_allocated safeguard anymore it just interferes with us having the proper dimensions.
See elementary/gala#1930
=> wayland: Don't use the revealer

src/PanelWindow.vala
Multiply the size with the scale factor to have the pixel size.
=> PanelWindow: send the right size to the compositor

data/wingpanel.metainfo.xml.in, src/Application.vala
Fixes #530 
This was previously done because we were depending on our stylesheet for panel styles. Styles live here now and there's some issues in some indicators with Adwaita still, but for the most part things are general fine :shrug:
=> Application: don't hardcode theme

lib/IndicatorManager.vala, src/PanelWindow.vala, src/Services/BackgroundManager.vala, wingpanel-interface/BackgroundManager.vala, wingpanel-interface/DBusServer.vala, wingpanel-interface/Utils.vala
Includes a little cleanup in gala plugin to make sure we always use the primary monitor
=> Fix deprecations and cleanup

src/PanelWindow.vala
Turns out we don't need to manually multiply anything :)
Otherwise we get very weird sizes
=> Fix fractional scaling

data/wingpanel.metainfo.xml.in
From [ihor_ck's comment](https://l10n.elementary.io/translate/wingpanel/wingpanel-extra/en/?q=has:comment#comments) on Weblate:
> Typo: scoll -> scroll
This typo is in the release note of a previous release; feel free to close if we shouldn't edit release notes that already published.
=> metainfo: Fix typo 'scoll' -> 'scroll'

src/Services/PopoverManager.vala
Fixes https://github.com/elementary/wingpanel/issues/519
=> Reset indicator selection when popover is closed

debian/control
Runtime depends on Gala for positioning, background, etc.
Presumably version 8 since we're not building Gala in daily for OS 7 anymore: https://code.launchpad.net/~elementary-os/+recipe/gala-daily
=> Control: runtime depends on Gala 8

data/wingpanel.metainfo.xml.in
I'd like to release 8.0.2 as requested in https://github.com/elementary/wingpanel/pull/593#issuecomment-2634930702.
I didn't summarize changes in #593 in the release note because it is an under-the-hood change.
=> Metainfo: add 8.0.2 release notes

src/PanelWindow.vala
Changed condition to define right actual panel height with scale factor to prevent the overlay panel to other window in full mode.
Fixes #594
=> ISSUE-594 fix panel actual_height with scale factor

lib/meson.build, lib/wingpanel-8.deps
I did here what granite did. I'm not to familiar with this stuff so let me know if something looks off :sweat_smile: 
Also I wonder do we even want this? I guess for porting it's useful to not overwrite old indicators but in the end we should probably just overwrite them? So basically revert this commit?
=> Rename lib to wingpanel-8

lib/PopoverMenuItem.vala, lib/meson.build
Adds a PopoverMenuItem widget since Gtk.ModelButton is private in GTK4. Saves us some work since every indicator has at least one settings item at the bottom
=> Add PopoverMenuItem

src/Widgets/Panel.vala
elementary's default implementation felt very heavy - you have to scroll a lot before it picks up anything, and the experience of going immediately a few workspaces left or right feels frustrating
The icon is too slow and keyboard not always in reach, so i use that feature daily.
"1" and "2" allows for a few misinputs (such as when mousewheel is between two notches somehow), but also picks up quickly enough user intent to react and switch
From using it a few days, ive set on "1" as "2" sometimes ignored valid inputs still. (roughly on my mouse thats the amount of notches that can be scrolled without causing a switch- I am not sure if other mouses would be different)
you cannot "scroll" too hard and go more than one workspace because the panel ignores further scrolling until the new …
=> Snappier "top panel workspace scroll"

wingpanel-interface/BackgroundManager.vala
Goes with https://github.com/elementary/gala/pull/2429
=> Use translucent style with fullscreen window
